language: java

jdk:
    - oraclejdk8
    - oraclejdk9

script:
    - ant

notifications:
        email:
                recipients:
                        - wiiaboo@gmail.com
                on_success: change
                on_failure: always
